name: Build docker images

on:
    workflow_dispatch:

jobs:
    multi-registries:
        runs-on: ubuntu-20.04
        steps:
            - name: Get current date
              id: current_date_time
              uses: Kaven-Universe/github-action-current-date-time@v1.1.0
              with:
                  format: "YYYYMMDDHHmmss"
            - name: Checkout
              uses: actions/checkout@v3
            - name: Docker meta
              id: docker_meta
              uses: crazy-max/ghaction-docker-meta@v4
              with:
                  images: kavenzero/kaven-proxy
                  tags: |
                    type=semver,pattern={{version}}
                    type=ref,event=branch
                    type=raw,value=${{ steps.current_date_time.outputs.time }}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-
            - name: Login to DockerHub
              if: github.repository == 'Kaven-Universe/kaven-proxy'
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER  }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Login to GitHub Container Registry
              if: github.repository == 'Kaven-Universe/kaven-proxy'
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64
                  push: ${{ github.repository == 'Kaven-Universe/kaven-proxy' }}
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
